config/routes.rb
Rails.application.routes.draw do  
  resources :notifications
  resources :produit_magasins
  resources :roles
  resources :magasins
  resources :venteproduits
  resources :ventes
  resources :users
  resources :inventairestocks
  resources :produits
  resources :familles
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/produit_magasin.rb
class ProduitMagasin < ApplicationRecord
  belongs_to :produit
  belongs_to :magasin
end

app/controllers/produit_magasins_controller.rb
class ProduitMagasinsController < ApplicationController
  before_action :set_produit_magasin, only: [:show, :edit, :update, :destroy]

  # GET /produit_magasins
  def index
    @produit_magasins = ProduitMagasin.all
  end

  # GET /produit_magasins/1
  def show
  end

  # GET /produit_magasins/new
  def new
    @produit_magasin = ProduitMagasin.new
  end

  # GET /produit_magasins/1/edit
  def edit
  end

  # POST /produit_magasins
  def create
    @produit_magasin = ProduitMagasin.new(produit_magasin_params)

    if @produit_magasin.save
      redirect_to @produit_magasin, notice: 'Produit magasin was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /produit_magasins/1
  def update
    if @produit_magasin.update(produit_magasin_params)
      redirect_to @produit_magasin, notice: 'Produit magasin was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /produit_magasins/1
  def destroy
    @produit_magasin.destroy
    redirect_to produit_magasins_url, notice: 'Produit magasin was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produit_magasin
      @produit_magasin = ProduitMagasin.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def produit_magasin_params
      params.require(:produit_magasin).permit(:qte, :produit_id, :magasin_id)
    end
end

app/helpers/produit_magasins_helper.rb
module ProduitMagasinsHelper
end

app/views/produit_magasins/_form.html.erb
<%= form_with(model: produit_magasin, local: true) do |form| %>
  <% if produit_magasin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produit_magasin.errors.count, "error") %> prohibited this produit_magasin from being saved:</h2>

      <ul>
        <% produit_magasin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :qte %>
    <%= form.number_field :qte %>
  </div>

  <div class="field">
    <%= form.label :produit_id %>
    <%= form.text_field :produit_id %>
  </div>

  <div class="field">
    <%= form.label :magasin_id %>
    <%= form.text_field :magasin_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/produit_magasins/edit.html.erb
<h1>Editing Produit Magasin</h1>

<%= render 'form', produit_magasin: @produit_magasin %>

<%= link_to 'Show', @produit_magasin %> |
<%= link_to 'Back', produit_magasins_path %>

app/views/produit_magasins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produit Magasins</h1>

<table>
  <thead>
    <tr>
      <th>Qte</th>
      <th>Produit</th>
      <th>Magasin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produit_magasins.each do |produit_magasin| %>
      <tr>
        <td><%= produit_magasin.qte %></td>
        <td><%= produit_magasin.produit_id %></td>
        <td><%= produit_magasin.magasin_id %></td>
        <td><%= link_to 'Show', produit_magasin %></td>
        <td><%= link_to 'Edit', edit_produit_magasin_path(produit_magasin) %></td>
        <td><%= link_to 'Destroy', produit_magasin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produit Magasin', new_produit_magasin_path %>

app/views/produit_magasins/new.html.erb
<h1>New Produit Magasin</h1>

<%= render 'form', produit_magasin: @produit_magasin %>

<%= link_to 'Back', produit_magasins_path %>

app/views/produit_magasins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Qte:</strong>
  <%= @produit_magasin.qte %>
</p>

<p>
  <strong>Produit:</strong>
  <%= @produit_magasin.produit_id %>
</p>

<p>
  <strong>Magasin:</strong>
  <%= @produit_magasin.magasin_id %>
</p>

<%= link_to 'Edit', edit_produit_magasin_path(@produit_magasin) %> |
<%= link_to 'Back', produit_magasins_path %>